name: firebase_auth_token
description: Extract user from verified Firebase Auth id token. The Firebase public key is cached and updated automatically.
homepage: https://github.com/Gerrel/firebase_auth_token
version: 1.0.5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  jose: ^0.3.4
  synchronized: ^3.1.0
  
dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.5
  
  
